"""Sample pharma MedInfo FAQ data for 6 drug products."""

DOC1 = {
    "filename": "CardioClear_XR_FAQ.pdf",
    "title": "CardioClear XR (Metopravil Succinate) — Medical Information FAQ",
    "subtitle": "Cardiovascular Therapeutics Division | Document Version 4.1 | Effective: January 2026",
    "sections": [
        {"heading": "1. General Information", "qas": [
            {"q": "What is CardioClear XR and what is it indicated for?",
             "a": "CardioClear XR (metopravil succinate) is an extended-release selective beta-1 adrenergic receptor blocker indicated for the treatment of essential hypertension in adults, chronic stable angina pectoris, and as adjunctive therapy in stable NYHA Class II-III heart failure."},
            {"q": "What are the available dosage forms and strengths of CardioClear XR?",
             "a": "CardioClear XR is available as extended-release tablets in the following strengths: 25 mg, 50 mg, 100 mg, and 200 mg. Tablets are film-coated and scored for flexible dosing."},
            {"q": "What is the recommended starting dose for hypertension?",
             "a": "The recommended starting dose for hypertension is 50 mg once daily. The dose may be titrated at weekly intervals up to a maximum of 200 mg once daily based on blood pressure response."},
            {"q": "Can CardioClear XR be crushed or split?",
             "a": "CardioClear XR tablets may be scored at the breakline but must not be crushed or chewed, as this would compromise the extended-release mechanism and result in rapid drug release."},
        ]},
        {"heading": "2. Clinical Pharmacology", "qas": [
            {"q": "What is the mechanism of action of CardioClear XR?",
             "a": "Metopravil succinate is a selective beta-1 adrenergic receptor antagonist. At therapeutic doses, it selectively blocks beta-1 receptors in cardiac tissue, reducing heart rate, myocardial contractility, and cardiac output, thereby lowering blood pressure. It has minimal activity at beta-2 receptors at recommended doses."},
            {"q": "What is the bioavailability of CardioClear XR?",
             "a": "The absolute oral bioavailability of CardioClear XR is approximately 45-50% due to first-pass hepatic metabolism. Peak plasma concentrations are achieved at approximately 6-8 hours post-dose with the extended-release formulation."},
            {"q": "What is the elimination half-life?",
             "a": "The elimination half-life of metopravil from CardioClear XR is approximately 12-16 hours, supporting once-daily dosing. Steady-state plasma concentrations are achieved within 3-4 days of repeated dosing."},
        ]},
        {"heading": "3. Dosage Adjustments", "qas": [
            {"q": "What dosage adjustments are required for patients with renal impairment?",
             "a": "Dosage adjustments based on renal function are recommended as follows:",
             "table": {"headers": ["Creatinine Clearance (mL/min)", "Recommended Dose", "Monitoring"],
                       "rows": [["≥60", "No adjustment required", "Standard monitoring"],
                                ["30-59", "Maximum 100 mg once daily", "Monitor BP and HR weekly"],
                                ["15-29", "Maximum 50 mg once daily", "Monitor BP, HR, and renal function bi-weekly"],
                                ["<15 or Dialysis", "25 mg once daily; administer post-dialysis", "Close clinical monitoring required"]]}},
            {"q": "Are dosage adjustments needed in hepatic impairment?",
             "a": "In patients with mild hepatic impairment (Child-Pugh A), no dosage adjustment is required. In moderate hepatic impairment (Child-Pugh B), the starting dose should be reduced to 25 mg once daily with a maximum dose of 100 mg. CardioClear XR is contraindicated in patients with severe hepatic impairment (Child-Pugh C)."},
            {"q": "Is CardioClear XR safe for use in elderly patients?",
             "a": "CardioClear XR may be used in elderly patients (≥65 years). A lower starting dose of 25 mg once daily is recommended due to the higher prevalence of decreased hepatic, renal, or cardiac function. Dose titration should be performed cautiously."},
        ]},
        {"heading": "4. Safety and Adverse Reactions", "qas": [
            {"q": "What are the most commonly reported adverse reactions?",
             "a": "The most commonly reported adverse reactions in clinical trials (incidence ≥5%) were:",
             "table": {"headers": ["Adverse Reaction", "CardioClear XR (N=1,247)", "Placebo (N=621)"],
                       "rows": [["Fatigue", "9.2%", "3.4%"], ["Dizziness", "7.8%", "2.9%"],
                                ["Bradycardia", "6.5%", "1.2%"], ["Nausea", "5.3%", "2.1%"],
                                ["Cold extremities", "5.1%", "1.8%"]]}},
            {"q": "What are the contraindications for CardioClear XR?",
             "a": "CardioClear XR is contraindicated in patients with: (1) heart rate <50 bpm prior to treatment initiation, (2) second- or third-degree atrioventricular block without a pacemaker, (3) decompensated heart failure requiring IV inotropic therapy, (4) cardiogenic shock, (5) sick sinus syndrome without a pacemaker, and (6) known hypersensitivity to metopravil or any excipient."},
            {"q": "Can CardioClear XR be abruptly discontinued?",
             "a": "No. Abrupt discontinuation of CardioClear XR should be avoided, particularly in patients with coronary artery disease. Sudden cessation may exacerbate angina, precipitate myocardial infarction, or trigger ventricular arrhythmias. The dose should be tapered over 1-2 weeks under medical supervision."},
            {"q": "Is CardioClear XR safe during pregnancy?",
             "a": "CardioClear XR is classified as Pregnancy Category D. Beta-blockers may cause fetal bradycardia, hypoglycemia, and growth restriction. Use during pregnancy is recommended only when the potential benefit justifies the potential risk to the fetus. Neonates exposed in utero should be monitored for 48-72 hours post-delivery."},
        ]},
        {"heading": "5. Drug Interactions", "qas": [
            {"q": "What are the significant drug interactions with CardioClear XR?",
             "a": "Clinically significant drug interactions include:",
             "table": {"headers": ["Interacting Drug", "Effect", "Recommendation"],
                       "rows": [["Verapamil / Diltiazem", "Additive negative chronotropic and inotropic effects", "Avoid concomitant use"],
                                ["CYP2D6 inhibitors (fluoxetine, paroxetine)", "Increased metopravil plasma levels", "Consider dose reduction"],
                                ["Clonidine", "Risk of rebound hypertension on withdrawal", "Discontinue CardioClear XR several days before clonidine withdrawal"],
                                ["NSAIDs", "May attenuate antihypertensive effect", "Monitor blood pressure closely"],
                                ["Insulin / Oral hypoglycemics", "May mask hypoglycemic symptoms", "Monitor blood glucose"]]}},
            {"q": "Can CardioClear XR be used with other antihypertensives?",
             "a": "Yes. CardioClear XR may be used concomitantly with ACE inhibitors, ARBs, or diuretics for additive blood pressure lowering. However, concomitant use with non-dihydropyridine calcium channel blockers (verapamil, diltiazem) is not recommended due to the risk of severe bradycardia and heart block."},
            {"q": "Does food affect the absorption of CardioClear XR?",
             "a": "Food does not significantly affect the rate or extent of absorption of CardioClear XR. The medication may be taken with or without food. However, consistent administration with respect to meals is recommended to maintain stable plasma levels."},
        ]},
    ]
}

DOC2 = {
    "filename": "OncoShield_IV_FAQ.pdf",
    "title": "OncoShield IV (Pembrixumab) — Medical Information FAQ",
    "subtitle": "Oncology Division | Document Version 3.0 | Effective: March 2026",
    "sections": [
        {"heading": "1. General Information", "qas": [
            {"q": "What is OncoShield IV and what is it indicated for?",
             "a": "OncoShield IV (pembrixumab) is a humanized monoclonal antibody directed against programmed death receptor-1 (PD-1). It is indicated for: (1) unresectable or metastatic melanoma, (2) metastatic non-small cell lung cancer (NSCLC) with PD-L1 expression ≥50%, (3) recurrent or metastatic head and neck squamous cell carcinoma (HNSCC), and (4) locally advanced or metastatic urothelial carcinoma."},
            {"q": "How is OncoShield IV supplied?",
             "a": "OncoShield IV is supplied as a sterile, preservative-free, clear to slightly opalescent, colorless to slightly yellow solution. It is available as 100 mg/4 mL (25 mg/mL) single-dose vials. Each carton contains one vial. Store refrigerated at 2°C to 8°C. Do not freeze or shake."},
            {"q": "What is the recommended dosing regimen?",
             "a": "The recommended dose of OncoShield IV is 200 mg administered as an intravenous infusion over 30 minutes every 3 weeks (Q3W), or 400 mg administered over 30 minutes every 6 weeks (Q6W). Treatment should continue until disease progression, unacceptable toxicity, or up to a maximum of 24 months in patients without disease progression."},
        ]},
        {"heading": "2. Administration and Preparation", "qas": [
            {"q": "How should OncoShield IV be prepared for infusion?",
             "a": "Withdraw the required volume from the vial(s) and transfer to an intravenous container containing 0.9% Sodium Chloride Injection to prepare a diluted solution with a final concentration between 1 mg/mL and 10 mg/mL. Mix by gentle inversion; do not shake. Inspect visually for particulate matter and discoloration prior to administration. Discard any unused portion remaining in the vial."},
            {"q": "What is the infusion time and can it be adjusted?",
             "a": "The initial infusion should be administered over 30 minutes. If the first infusion is well tolerated, subsequent infusions may be administered over a minimum of 30 minutes. Do not administer as an intravenous push or bolus injection. If a mild or moderate infusion reaction occurs, slow or interrupt the infusion and administer appropriate medical management."},
            {"q": "What is the stability of the diluted solution?",
             "a": "The diluted solution may be stored at room temperature (20°C to 25°C) for no more than 6 hours from the time of preparation, including infusion time. If refrigerated (2°C to 8°C), the diluted solution is stable for no more than 24 hours from the time of preparation. Allow the refrigerated solution to come to room temperature prior to administration."},
        ]},
        {"heading": "3. Immune-Related Adverse Reactions", "qas": [
            {"q": "What immune-related adverse reactions have been reported?",
             "a": "Immune-related adverse reactions (irARs) reported in clinical trials include:",
             "table": {"headers": ["Immune-Related AR", "Any Grade", "Grade 3-4"],
                       "rows": [["Hypothyroidism", "10.1%", "0.2%"], ["Hyperthyroidism", "4.9%", "0.1%"],
                                ["Pneumonitis", "3.4%", "1.0%"], ["Colitis", "1.8%", "0.7%"],
                                ["Hepatitis", "1.2%", "0.5%"], ["Nephritis", "0.6%", "0.2%"],
                                ["Type 1 Diabetes Mellitus", "0.3%", "0.1%"]]}},
            {"q": "How should immune-related pneumonitis be managed?",
             "a": "For Grade 2 pneumonitis, withhold OncoShield IV and initiate corticosteroids (prednisone 1-2 mg/kg/day or equivalent). Resume OncoShield IV upon improvement to Grade 0-1 and completion of corticosteroid taper over ≥4 weeks. For Grade 3-4 pneumonitis, permanently discontinue OncoShield IV and initiate high-dose corticosteroids (methylprednisolone 2-4 mg/kg/day IV). Consider additional immunosuppression if no improvement within 48-72 hours."},
            {"q": "What thyroid monitoring is recommended during treatment?",
             "a": "Thyroid function tests (TSH and free T4) should be performed at baseline, prior to each treatment cycle for the first 6 months, and then every 2 cycles thereafter. If hypothyroidism develops, initiate thyroid hormone replacement therapy as clinically indicated. If hyperthyroidism develops, manage symptomatically and consider endocrinology referral."},
        ]},
        {"heading": "4. Special Populations", "qas": [
            {"q": "Can OncoShield IV be used in patients with autoimmune diseases?",
             "a": "Patients with active autoimmune disease requiring systemic immunosuppressive therapy were excluded from clinical trials. OncoShield IV may be considered in patients with controlled autoimmune conditions not requiring systemic immunosuppression, with close monitoring. The potential risk of autoimmune flare must be weighed against the anticipated benefit."},
            {"q": "Is OncoShield IV safe during pregnancy and lactation?",
             "a": "OncoShield IV may cause fetal harm based on its mechanism of action and animal data. Verify pregnancy status prior to initiation. Advise females of reproductive potential to use effective contraception during treatment and for 4 months after the last dose. It is not known whether pembrixumab is excreted in human milk. Advise women not to breastfeed during treatment and for 4 months after the last dose."},
            {"q": "Is dose adjustment required for renal or hepatic impairment?",
             "a": "No dose adjustment is required for patients with mild or moderate renal impairment (CrCl 30-89 mL/min) or mild hepatic impairment (total bilirubin ≤ULN and AST >ULN, or total bilirubin 1-1.5× ULN). OncoShield IV has not been studied in patients with severe renal impairment (CrCl <30 mL/min) or moderate-to-severe hepatic impairment."},
        ]},
        {"heading": "5. Biomarker Testing", "qas": [
            {"q": "Is PD-L1 testing required before initiating OncoShield IV?",
             "a": "PD-L1 testing using an FDA-approved companion diagnostic is required for NSCLC (TPS ≥50% for first-line monotherapy or TPS ≥1% for combination therapy). For melanoma, HNSCC, and urothelial carcinoma, PD-L1 testing is not required for treatment eligibility but may provide prognostic information."},
            {"q": "What is the recommended PD-L1 testing assay?",
             "a": "The recommended companion diagnostic is the PharmaScore PD-L1 IHC 22C3 assay performed on formalin-fixed, paraffin-embedded (FFPE) tumor tissue. The Tumor Proportion Score (TPS) is calculated as the percentage of viable tumor cells showing partial or complete membrane staining at any intensity. A minimum of 100 viable tumor cells must be present for the specimen to be evaluable."},
            {"q": "Can liquid biopsy be used for PD-L1 assessment?",
             "a": "Currently, PD-L1 expression assessment via liquid biopsy (circulating tumor cells or cell-free DNA) is not validated as a companion diagnostic for OncoShield IV treatment selection. Tissue-based PD-L1 IHC testing using the approved companion diagnostic assay remains the standard. Clinical trials evaluating liquid biopsy concordance are ongoing."},
            {"q": "What is the tumor mutational burden (TMB) threshold?",
             "a": "OncoShield IV is indicated for the treatment of adult patients with unresectable or metastatic tumor mutational burden-high (TMB-H) solid tumors, defined as ≥10 mutations per megabase (mut/Mb), as determined by an FDA-approved test. TMB should be assessed using the FoundationScope CDx assay on FFPE tumor tissue."},
        ]},
    ]
}

DOC3 = {
    "filename": "GlucoBalance_Plus_FAQ.pdf",
    "title": "GlucoBalance Plus (Semaglipride) — Medical Information FAQ",
    "subtitle": "Metabolic & Endocrinology Division | Document Version 5.2 | Effective: February 2026",
    "sections": [
        {"heading": "1. General Information", "qas": [
            {"q": "What is GlucoBalance Plus and what is it indicated for?",
             "a": "GlucoBalance Plus (semaglipride) is a glucagon-like peptide-1 (GLP-1) receptor agonist indicated as an adjunct to diet and exercise to improve glycemic control in adults with type 2 diabetes mellitus. It is also indicated to reduce the risk of major adverse cardiovascular events (MACE) in adults with type 2 diabetes and established cardiovascular disease."},
            {"q": "What are the available dosage forms?",
             "a": "GlucoBalance Plus is available as a solution for subcutaneous injection in the following presentations: (1) 0.25 mg/0.5 mL pre-filled pen, (2) 0.5 mg/0.5 mL pre-filled pen, (3) 1.0 mg/0.5 mL pre-filled pen, and (4) 2.0 mg/0.5 mL pre-filled pen. Each pen delivers a single fixed dose and is for single-patient use only."},
            {"q": "What is the recommended dose escalation schedule?",
             "a": "The dose escalation schedule is as follows:",
             "table": {"headers": ["Week", "Dose", "Purpose"],
                       "rows": [["Weeks 1-4", "0.25 mg once weekly", "Initiation dose (not therapeutic)"],
                                ["Weeks 5-8", "0.5 mg once weekly", "First therapeutic dose"],
                                ["Weeks 9-12", "1.0 mg once weekly", "Dose escalation if needed"],
                                ["Week 13+", "2.0 mg once weekly", "Maximum dose if further glycemic control needed"]]}},
        ]},
        {"heading": "2. Clinical Efficacy", "qas": [
            {"q": "What HbA1c reduction can be expected with GlucoBalance Plus?",
             "a": "In the BALANCE-1 pivotal trial (N=1,961), GlucoBalance Plus demonstrated the following HbA1c reductions from baseline at 56 weeks:",
             "table": {"headers": ["Treatment Group", "Baseline HbA1c", "Change from Baseline", "Patients Achieving <7%"],
                       "rows": [["GlucoBalance Plus 0.5 mg", "8.1%", "-1.2%", "58%"],
                                ["GlucoBalance Plus 1.0 mg", "8.0%", "-1.6%", "72%"],
                                ["GlucoBalance Plus 2.0 mg", "8.1%", "-1.9%", "81%"],
                                ["Placebo", "8.0%", "-0.1%", "15%"]]}},
            {"q": "Does GlucoBalance Plus cause weight loss?",
             "a": "Yes. In the BALANCE clinical trial program, GlucoBalance Plus demonstrated statistically significant weight reduction compared to placebo. At the 2.0 mg dose, mean body weight reduction was 5.9 kg (approximately 6.2% of baseline body weight) at 56 weeks compared to 1.3 kg with placebo (p<0.001). Weight reduction was primarily attributed to decreased appetite and caloric intake."},
            {"q": "What cardiovascular outcomes data are available?",
             "a": "The BALANCE-CV trial (N=3,297; median follow-up 2.1 years) demonstrated that GlucoBalance Plus reduced the risk of first occurrence of MACE (cardiovascular death, non-fatal myocardial infarction, or non-fatal stroke) by 26% compared to placebo (HR 0.74; 95% CI: 0.58-0.95; p=0.017). This benefit was primarily driven by reductions in non-fatal stroke (39% relative risk reduction) and non-fatal MI (26% relative risk reduction)."},
        ]},
        {"heading": "3. Safety Profile", "qas": [
            {"q": "What are the most common adverse reactions?",
             "a": "The most common adverse reactions reported in ≥5% of patients treated with GlucoBalance Plus were:",
             "table": {"headers": ["Adverse Reaction", "0.5 mg (N=822)", "1.0 mg (N=834)", "2.0 mg (N=839)", "Placebo (N=831)"],
                       "rows": [["Nausea", "15.8%", "18.2%", "21.3%", "6.1%"],
                                ["Diarrhea", "8.5%", "10.1%", "11.4%", "4.5%"],
                                ["Vomiting", "5.0%", "7.3%", "9.2%", "2.3%"],
                                ["Decreased appetite", "5.2%", "7.8%", "9.8%", "2.7%"],
                                ["Constipation", "5.0%", "5.1%", "5.6%", "3.2%"],
                                ["Injection site reactions", "5.4%", "5.0%", "5.8%", "3.9%"]]}},
            {"q": "Is there a risk of pancreatitis?",
             "a": "Acute pancreatitis has been reported in clinical trials and post-marketing experience with GLP-1 receptor agonists. In the GlucoBalance Plus clinical program, pancreatitis was reported in 0.3% of treated patients. Instruct patients to report persistent, severe abdominal pain that may radiate to the back. If pancreatitis is suspected, discontinue GlucoBalance Plus promptly and initiate appropriate management."},
            {"q": "Is there a risk of thyroid C-cell tumors?",
             "a": "In rodent studies, semaglipride caused thyroid C-cell tumors at clinically relevant exposures. It is unknown whether GlucoBalance Plus causes thyroid C-cell tumors in humans. GlucoBalance Plus is contraindicated in patients with a personal or family history of medullary thyroid carcinoma (MTC) or Multiple Endocrine Neoplasia syndrome type 2 (MEN 2). Counsel patients regarding the potential risk and symptoms of thyroid tumors."},
        ]},
        {"heading": "4. Administration and Storage", "qas": [
            {"q": "How should GlucoBalance Plus be administered?",
             "a": "GlucoBalance Plus should be injected subcutaneously in the abdomen, thigh, or upper arm once weekly on the same day each week, at any time of day, with or without meals. The injection site should be rotated with each dose. If a dose is missed, administer within 5 days of the missed dose. If more than 5 days have passed, skip the missed dose and administer the next dose on the regularly scheduled day."},
            {"q": "What are the storage requirements?",
             "a": "Prior to first use, GlucoBalance Plus pens should be stored refrigerated at 2°C to 8°C (36°F to 46°F). Do not freeze; discard if frozen. After first use, pens may be stored at room temperature (up to 30°C / 86°F) or refrigerated for up to 56 days. Protect from light by keeping the pen cap on when not in use. Discard the pen 56 days after first use, even if unused medication remains."},
            {"q": "Can GlucoBalance Plus be used with insulin?",
             "a": "GlucoBalance Plus may be used concomitantly with basal insulin. When initiating GlucoBalance Plus in patients on insulin, consider reducing the insulin dose by 20% to mitigate the risk of hypoglycemia. GlucoBalance Plus should not be used in combination with prandial insulin or other GLP-1 receptor agonists. The combination of GlucoBalance Plus and insulin has not been studied in patients with type 1 diabetes."},
            {"q": "Can GlucoBalance Plus be mixed with other injectable medications?",
             "a": "No. GlucoBalance Plus must not be mixed with other injectable medications. If GlucoBalance Plus and insulin are both prescribed, they must be administered as separate injections. The two injections may be given in the same body region but should not be adjacent to each other (maintain at least 5 cm between injection sites)."},
        ]},
    ]
}

DOC4 = {
    "filename": "ImmunoGuard_SC_FAQ.pdf",
    "title": "ImmunoGuard SC (Adalituzumab) — Medical Information FAQ",
    "subtitle": "Immunology Division | Document Version 6.0 | Effective: January 2026",
    "sections": [
        {"heading": "1. Indications and General Information", "qas": [
            {"q": "What is ImmunoGuard SC and what are its approved indications?",
             "a": "ImmunoGuard SC (adalituzumab) is a fully human recombinant IgG1 monoclonal antibody that specifically binds tumor necrosis factor-alpha (TNF-α). It is indicated for: (1) moderate-to-severe rheumatoid arthritis (RA), (2) active psoriatic arthritis (PsA), (3) active ankylosing spondylitis (AS), (4) moderate-to-severe chronic plaque psoriasis (PsO) in adults, (5) moderate-to-severe Crohn's disease (CD), and (6) moderate-to-severe ulcerative colitis (UC)."},
            {"q": "What dosage forms are available?",
             "a": "ImmunoGuard SC is available as a sterile, preservative-free solution for subcutaneous injection in the following presentations: (1) 40 mg/0.8 mL single-dose pre-filled syringe, (2) 40 mg/0.8 mL single-dose pre-filled pen (SureClick), and (3) 80 mg/0.8 mL single-dose pre-filled syringe for loading doses."},
            {"q": "What is the recommended dosing for rheumatoid arthritis?",
             "a": "For rheumatoid arthritis, the recommended dose is 40 mg administered subcutaneously every other week. Some patients with RA not receiving concomitant methotrexate may benefit from increasing the dosing frequency to 40 mg every week. Methotrexate, other non-biologic DMARDs, corticosteroids, NSAIDs, and/or analgesics may be continued during treatment."},
        ]},
        {"heading": "2. Pre-Treatment Screening", "qas": [
            {"q": "What screening tests are required before initiating ImmunoGuard SC?",
             "a": "The following screening tests are required before initiating ImmunoGuard SC:",
             "table": {"headers": ["Test", "Purpose", "Action if Positive"],
                       "rows": [["Tuberculin skin test (TST) or IGRA", "Screen for latent TB", "Treat latent TB before initiating"],
                                ["Hepatitis B serology (HBsAg, anti-HBs, anti-HBc)", "Screen for HBV infection", "Consult hepatologist; monitor if past infection"],
                                ["CBC with differential", "Baseline hematologic status", "Do not initiate if ANC <1,000/mm³"],
                                ["Hepatic panel", "Baseline liver function", "Do not initiate if ALT >5× ULN"],
                                ["Varicella immunity", "Assess vaccination need", "Vaccinate before initiation if non-immune"]]}},
            {"q": "How should latent tuberculosis be managed?",
             "a": "If latent tuberculosis is diagnosed, treatment with isoniazid (or alternative regimen per local guidelines) must be initiated at least 1 month before starting ImmunoGuard SC. Patients should complete the full course of TB prophylaxis. Monitor for signs and symptoms of active TB during and after treatment with ImmunoGuard SC, even in patients who tested negative for latent TB, as false-negative results can occur."},
            {"q": "Which vaccinations should be administered before treatment?",
             "a": "All age-appropriate vaccinations should be brought up to date before initiating ImmunoGuard SC. Live vaccines should be administered at least 4 weeks prior to starting treatment. Inactivated vaccines (including influenza and pneumococcal vaccines) may be given during treatment. Live vaccines should not be given concurrently with ImmunoGuard SC due to the risk of clinical infection from vaccine strains."},
        ]},
        {"heading": "3. Safety — Infections", "qas": [
            {"q": "What is the risk of serious infections with ImmunoGuard SC?",
             "a": "Serious infections, including sepsis, pneumonia, invasive fungal infections, and opportunistic infections, have been reported in patients receiving ImmunoGuard SC. In controlled clinical trials, the rate of serious infections was 4.7 per 100 patient-years in ImmunoGuard SC-treated patients compared to 2.7 per 100 patient-years in placebo-treated patients. Most serious infections occurred in patients on concomitant immunosuppressive therapy."},
            {"q": "What should be done if a serious infection develops?",
             "a": "If a patient develops a serious infection during treatment with ImmunoGuard SC, therapy should be discontinued until the infection is controlled. Appropriate antimicrobial therapy should be initiated promptly. ImmunoGuard SC should not be restarted until the infection has fully resolved and the patient is clinically stable. Consider the risks and benefits before reinitiation in patients with chronic or recurrent infections."},
            {"q": "Is there a risk of hepatitis B reactivation?",
             "a": "Yes. Reactivation of hepatitis B virus (HBV) has been reported in patients who are chronic HBV carriers treated with TNF-α inhibitors, including ImmunoGuard SC. Some cases have been fatal. Test patients for HBV infection before initiating treatment. For patients who are HBsAg-positive, consult a hepatologist before and during treatment. If HBV reactivation occurs, discontinue ImmunoGuard SC immediately and initiate appropriate antiviral therapy."},
        ]},
        {"heading": "4. Special Populations", "qas": [
            {"q": "Can ImmunoGuard SC be used in pediatric patients?",
             "a": "ImmunoGuard SC is approved for use in pediatric patients aged ≥2 years for polyarticular juvenile idiopathic arthritis and pediatric Crohn's disease. Dosing is weight-based:",
             "table": {"headers": ["Body Weight", "Induction Dose (Day 1)", "Dose from Day 15", "Maintenance Dose"],
                       "rows": [["≥40 kg", "160 mg", "80 mg", "40 mg every other week"],
                                ["<40 kg", "80 mg", "40 mg", "20 mg every other week"]]}},
            {"q": "Can ImmunoGuard SC be used during pregnancy?",
             "a": "ImmunoGuard SC crosses the placenta and has been detected in infant serum for up to 5 months after the mother's last dose. A pregnancy registry is available. Based on available data, no increased risk of major birth defects has been observed. However, infants exposed in utero may be at increased risk of infection. Avoid administration of live vaccines to infants exposed in utero for at least 5 months after the mother's last dose."},
            {"q": "Is ImmunoGuard SC compatible with breastfeeding?",
             "a": "Adalituzumab is present in breast milk at concentrations approximately 0.1-1% of maternal serum concentrations. Because monoclonal antibodies are large proteins that are likely degraded in the infant gastrointestinal tract, systemic exposure in a breastfed infant is expected to be negligible. The developmental and health benefits of breastfeeding should be considered along with the mother's clinical need for ImmunoGuard SC."},
            {"q": "Are there specific considerations for elderly patients?",
             "a": "No dose adjustment is required for patients aged 65 years and older. However, the incidence of serious infections in controlled clinical trials was higher among patients aged ≥65 (7.9 per 100 patient-years) compared to younger patients (4.1 per 100 patient-years). Exercise caution when treating elderly patients and monitor closely for signs of infection."},
        ]},
        {"heading": "5. Administration Guidance", "qas": [
            {"q": "How should patients self-administer ImmunoGuard SC?",
             "a": "Patients should be trained on proper subcutaneous injection technique before self-administration. Inject into the front of the thigh or lower abdomen (at least 5 cm from the navel). Rotate injection sites and avoid areas that are tender, bruised, red, or hard. Allow the pre-filled syringe or pen to reach room temperature (approximately 15-30 minutes) before injection. Do not remove the needle cap until ready to inject."},
            {"q": "What should patients do if they miss a dose?",
             "a": "If a dose of ImmunoGuard SC is missed, administer the dose as soon as possible. Then, take the next dose at the regularly scheduled time. Do not administer two doses on the same day. If it is close to the next scheduled dose, skip the missed dose and resume the regular dosing schedule."},
        ]},
    ]
}

DOC5 = {
    "filename": "NeuroCalm_ODT_FAQ.pdf",
    "title": "NeuroCalm ODT (Zolpitrazepam) — Medical Information FAQ",
    "subtitle": "Neuroscience Division | Document Version 2.8 | Effective: February 2026",
    "sections": [
        {"heading": "1. General Information", "qas": [
            {"q": "What is NeuroCalm ODT and what is it indicated for?",
             "a": "NeuroCalm ODT (zolpitrazepam) is a selective GABA-A receptor positive allosteric modulator available as an orally disintegrating tablet. It is indicated for the acute treatment of generalized anxiety disorder (GAD) in adults and for the short-term management of insomnia characterized by difficulty with sleep onset (maximum treatment duration: 4 weeks)."},
            {"q": "What are the available strengths?",
             "a": "NeuroCalm ODT is available as orally disintegrating tablets in 2.5 mg, 5 mg, and 10 mg strengths. Tablets are round, white to off-white, and are packaged in individually sealed blister packs to protect from moisture."},
            {"q": "How should NeuroCalm ODT be taken?",
             "a": "Place the tablet on the tongue immediately after removal from the blister pack with dry hands. The tablet will disintegrate within 10-15 seconds without need for water. Do not swallow the tablet whole. Do not push the tablet through the blister foil; peel back the foil to remove the tablet. For sleep onset insomnia, take immediately before bedtime with at least 7-8 hours of remaining sleep time."},
        ]},
        {"heading": "2. Clinical Pharmacology", "qas": [
            {"q": "What is the mechanism of action of NeuroCalm ODT?",
             "a": "Zolpitrazepam is a selective positive allosteric modulator of GABA-A receptors containing the α1, α2, and α3 subunits. Unlike classical benzodiazepines, it has minimal activity at α5-containing receptors, which is associated with reduced cognitive and memory impairment. The anxiolytic effect is primarily mediated through α2/α3 subunit modulation, while the hypnotic effect is mediated through α1 subunit modulation."},
            {"q": "What is the pharmacokinetic profile?",
             "a": "Key pharmacokinetic parameters of NeuroCalm ODT are:",
             "table": {"headers": ["Parameter", "Value"],
                       "rows": [["Time to peak plasma concentration (Tmax)", "15-30 minutes (ODT formulation)"],
                                ["Oral bioavailability", "72% (ODT) vs. 55% (conventional tablet)"],
                                ["Elimination half-life", "3.5-4.5 hours"],
                                ["Protein binding", "92%"],
                                ["Primary metabolism", "CYP3A4 (major), CYP2C9 (minor)"],
                                ["Active metabolites", "None"]]}},
            {"q": "Why is the ODT formulation preferred over a conventional tablet?",
             "a": "The orally disintegrating tablet formulation provides several advantages: (1) faster onset of action (Tmax 15-30 minutes vs. 45-60 minutes for conventional tablets) due to pre-gastric absorption through the buccal mucosa, (2) higher bioavailability (72% vs. 55%), (3) no need for water, enabling administration in any setting, and (4) reduced first-pass metabolism. These pharmacokinetic advantages are particularly beneficial for acute anxiety episodes requiring rapid symptom relief."},
        ]},
        {"heading": "3. Dosing and Special Populations", "qas": [
            {"q": "What is the recommended dosing for generalized anxiety disorder?",
             "a": "For generalized anxiety disorder, the recommended starting dose is 2.5 mg taken as needed, up to three times daily. The dose may be increased to 5 mg as needed based on clinical response and tolerability, with a maximum daily dose of 15 mg. For patients requiring regular daily dosing, reassess the need for continued treatment at least monthly."},
            {"q": "What is the recommended dosing for insomnia?",
             "a": "For sleep onset insomnia, the recommended dose is 5 mg taken once nightly immediately before bedtime. The dose may be increased to 10 mg if 5 mg is not effective. The lowest effective dose should be used. Treatment duration should not exceed 4 weeks. If insomnia persists beyond 4 weeks, re-evaluate the patient for underlying conditions contributing to sleep disturbance."},
            {"q": "Are dose adjustments needed for elderly patients?",
             "a": "Yes. In patients aged ≥65 years, the starting dose should be reduced to 2.5 mg for both anxiety and insomnia indications due to increased sensitivity and reduced clearance (50% lower clearance compared to younger adults). The maximum daily dose in elderly patients should not exceed 7.5 mg for anxiety and 5 mg for insomnia."},
            {"q": "Are dose adjustments needed in hepatic impairment?",
             "a": "Yes. Dose adjustments are required based on hepatic function:",
             "table": {"headers": ["Hepatic Impairment", "Anxiety Dose", "Insomnia Dose"],
                       "rows": [["Mild (Child-Pugh A)", "No adjustment needed", "No adjustment needed"],
                                ["Moderate (Child-Pugh B)", "Max 2.5 mg three times daily", "Max 5 mg nightly"],
                                ["Severe (Child-Pugh C)", "Contraindicated", "Contraindicated"]]}},
        ]},
        {"heading": "4. Safety and Warnings", "qas": [
            {"q": "What are the abuse and dependence risks?",
             "a": "NeuroCalm ODT is a Schedule IV controlled substance. Physical and psychological dependence can develop with prolonged use. In clinical studies of up to 12 weeks, withdrawal symptoms (anxiety rebound, tremor, insomnia) were observed in 8.4% of patients abruptly discontinued from NeuroCalm ODT compared to 2.1% with gradual taper. A gradual dose reduction over 1-2 weeks is recommended when discontinuing therapy."},
            {"q": "What are the effects on driving and operating machinery?",
             "a": "NeuroCalm ODT can impair mental alertness and motor coordination. Patients should be advised not to drive, operate heavy machinery, or engage in hazardous activities for at least 8 hours after taking the medication. Next-day impairment may occur, particularly with the 10 mg dose. If patients report next-day somnolence, consider reducing the dose."},
            {"q": "Can NeuroCalm ODT be used with alcohol?",
             "a": "No. Concomitant use of alcohol with NeuroCalm ODT is contraindicated. The combination enhances CNS depression, including sedation, respiratory depression, coma, and death. In pharmacokinetic studies, co-administration with alcohol (0.5 g/kg) increased the Cmax of zolpitrazepam by 30% and the AUC by 40%. Patients must be counseled to avoid all alcohol-containing beverages and products during treatment."},
            {"q": "What are the risks in patients with respiratory conditions?",
             "a": "NeuroCalm ODT should be used with caution in patients with compromised respiratory function, including chronic obstructive pulmonary disease (COPD), sleep apnea syndrome (moderate-to-severe), or acute respiratory insufficiency. Respiratory depression has been reported, primarily at higher doses or in combination with other CNS depressants. NeuroCalm ODT is contraindicated in patients with severe respiratory insufficiency."},
        ]},
        {"heading": "5. Drug Interactions", "qas": [
            {"q": "What are the significant drug interactions?",
             "a": "Clinically significant drug interactions include:",
             "table": {"headers": ["Drug / Class", "Effect", "Recommendation"],
                       "rows": [["Strong CYP3A4 inhibitors (ketoconazole, itraconazole)", "3-fold increase in zolpitrazepam exposure", "Reduce NeuroCalm ODT dose by 75%"],
                                ["Strong CYP3A4 inducers (rifampin, carbamazepine)", "80% decrease in zolpitrazepam exposure", "Avoid concomitant use"],
                                ["Opioids", "Additive CNS and respiratory depression", "Avoid concomitant use; if necessary, use lowest doses"],
                                ["Other benzodiazepines / sedatives", "Additive sedation", "Avoid concomitant use"],
                                ["Fluoxetine / fluvoxamine", "Moderate CYP3A4 inhibition; 50% increase in exposure", "Reduce NeuroCalm ODT dose by 50%"]]}},
            {"q": "Can NeuroCalm ODT be taken with food?",
             "a": "For the orally disintegrating tablet formulation, food does not significantly affect the extent of absorption (AUC), but may delay the time to peak concentration (Tmax) from 15-30 minutes to 45-60 minutes. For acute anxiety episodes where rapid onset is desired, administration in the fasted state is recommended. For insomnia, the tablet may be taken regardless of food intake as long as it is taken immediately before bedtime."},
        ]},
    ]
}

DOC6 = {
    "filename": "BreatheEasy_Inhaler_FAQ.pdf",
    "title": "BreatheEasy DPI (Flurimoterol / Budesonixa) — Medical Information FAQ",
    "subtitle": "Respiratory Division | Document Version 3.5 | Effective: March 2026",
    "sections": [
        {"heading": "1. Product Information", "qas": [
            {"q": "What is BreatheEasy DPI and what is it indicated for?",
             "a": "BreatheEasy DPI is a fixed-dose combination dry powder inhaler containing flurimoterol (a long-acting beta-2 agonist, LABA) and budesonixa (an inhaled corticosteroid, ICS). It is indicated for: (1) maintenance treatment of asthma in patients aged ≥12 years not adequately controlled on ICS alone, and (2) maintenance treatment of chronic obstructive pulmonary disease (COPD) to reduce exacerbations in patients with a history of exacerbations."},
            {"q": "What strengths are available?",
             "a": "BreatheEasy DPI is available in three strengths, each delivering per inhalation:",
             "table": {"headers": ["Strength", "Flurimoterol", "Budesonixa", "Indication"],
                       "rows": [["Low", "4.5 mcg", "80 mcg", "Asthma (Step 3)"],
                                ["Medium", "4.5 mcg", "160 mcg", "Asthma (Step 3-4)"],
                                ["High", "4.5 mcg", "320 mcg", "Asthma (Step 4-5) / COPD"]]}},
            {"q": "How many doses are in each inhaler?",
             "a": "Each BreatheEasy DPI inhaler contains 120 metered doses (60 days of treatment at the recommended dosing of 2 inhalations twice daily). The inhaler includes a built-in dose counter that counts down from 120 to 0. When the counter reaches 20 (highlighted in red), a new inhaler should be obtained. Discard the inhaler when the counter reads 0 or 12 months after removal from the foil pouch, whichever comes first."},
        ]},
        {"heading": "2. Dosing and Administration", "qas": [
            {"q": "What is the recommended dosing for asthma?",
             "a": "The recommended dosing for asthma in patients aged ≥12 years is 2 inhalations twice daily (morning and evening, approximately 12 hours apart). The appropriate strength should be selected based on asthma severity. Patients should rinse their mouth with water and spit after each administration to reduce the risk of oropharyngeal candidiasis. BreatheEasy DPI is not indicated for the relief of acute bronchospasm."},
            {"q": "What is the recommended dosing for COPD?",
             "a": "For COPD, the recommended dose is BreatheEasy DPI High Strength (flurimoterol 4.5 mcg / budesonixa 320 mcg): 2 inhalations twice daily. This is the only strength approved for COPD. The maximum recommended dose is 2 inhalations twice daily of the High Strength formulation. Exceeding this dose does not provide additional benefit and increases the risk of systemic corticosteroid effects."},
            {"q": "How should the DPI device be used?",
             "a": "Instructions for use: (1) Open the cover fully until it clicks. (2) Hold the inhaler upright and slide the lever away from you until it clicks — this loads a dose. (3) Breathe out fully (away from the inhaler). (4) Place the mouthpiece between your lips and seal tightly. (5) Inhale deeply and forcefully through the mouth. (6) Remove the inhaler and hold your breath for 10 seconds. (7) If a second inhalation is needed, repeat steps 2-6. (8) Close the cover. Always store the inhaler in a dry place with the cover closed."},
            {"q": "What inspiratory flow rate is needed for the DPI device?",
             "a": "The BreatheEasy DPI device requires a minimum peak inspiratory flow rate (PIFR) of 30 L/min for adequate drug delivery. Optimal drug delivery is achieved at PIFR ≥60 L/min. Patients with severe airflow limitation or those unable to generate adequate inspiratory flow may not receive the full dose. Consider alternative delivery systems (e.g., metered-dose inhaler with spacer or nebulizer) for patients with PIFR <30 L/min."},
        ]},
        {"heading": "3. Safety Profile", "qas": [
            {"q": "What are the most common adverse reactions?",
             "a": "The most common adverse reactions reported in ≥3% of patients in clinical trials were:",
             "table": {"headers": ["Adverse Reaction", "BreatheEasy DPI (N=1,432)", "ICS alone (N=714)"],
                       "rows": [["Nasopharyngitis", "7.2%", "6.8%"], ["Oral candidiasis", "5.1%", "3.9%"],
                                ["Headache", "4.8%", "4.2%"], ["Upper respiratory tract infection", "4.3%", "3.8%"],
                                ["Dysphonia", "3.2%", "1.9%"], ["Muscle cramps", "3.0%", "0.8%"]]}},
            {"q": "What is the risk of pneumonia in COPD patients?",
             "a": "In COPD trials, the incidence of pneumonia was 6.2% in patients receiving BreatheEasy DPI High Strength compared to 3.4% in patients receiving LABA alone over 12 months. Risk factors for pneumonia include current smoking, history of prior pneumonia, BMI <25 kg/m², and severe airflow limitation (FEV1 <50% predicted). Monitor COPD patients for signs of pneumonia, as clinical features may overlap with COPD exacerbations."},
            {"q": "Does BreatheEasy DPI affect bone density?",
             "a": "Long-term use of inhaled corticosteroids may be associated with reduced bone mineral density. In a 2-year study, patients receiving BreatheEasy DPI High Strength showed a mean lumbar spine BMD decrease of 0.4% compared to 0.1% with LABA alone. Patients at risk for osteoporosis should be monitored with periodic bone density assessments and should follow standard preventive measures including adequate calcium and vitamin D intake and weight-bearing exercise."},
        ]},
        {"heading": "4. Special Populations and Precautions", "qas": [
            {"q": "Can BreatheEasy DPI be used during pregnancy?",
             "a": "Limited data from clinical trials in pregnant women are insufficient to inform a drug-associated risk. In animal reproduction studies, budesonixa administered by inhalation at doses up to 3 times the maximum recommended human dose (MRHD) did not cause adverse developmental effects. Poorly controlled asthma during pregnancy is associated with perinatal complications. The potential benefits should be weighed against potential risks. Pregnant asthma patients should continue controller therapy under physician guidance."},
            {"q": "Can BreatheEasy DPI be used in pediatric patients?",
             "a": "BreatheEasy DPI is approved for use in patients aged ≥12 years. The safety and efficacy in children <12 years have not been established. Growth velocity should be monitored in adolescent patients receiving inhaled corticosteroids, as a transient reduction in growth velocity (approximately 1 cm/year) may be observed during the first 1-2 years of treatment. This effect is generally small, and the long-term effect on final adult height is unknown."},
            {"q": "What precautions apply to patients being transferred from systemic corticosteroids?",
             "a": "Patients transferring from systemic corticosteroids to BreatheEasy DPI are at risk of adrenal insufficiency. Taper systemic corticosteroids slowly (reduce prednisone by no more than 2.5 mg/week). Monitor patients for signs of adrenal insufficiency (fatigue, weakness, nausea, hypotension) during and after transfer. During periods of stress or acute asthma exacerbation, supplemental systemic corticosteroids may be needed. Advise patients to carry a medical alert card indicating their need for supplemental systemic steroids during stress."},
            {"q": "How should the inhaler device be cleaned?",
             "a": "Clean the mouthpiece of the inhaler once weekly. Wipe the outside of the mouthpiece with a clean, dry cloth or tissue. Do not wash the inhaler or place any part of it in water, as moisture can affect drug delivery. If the inhaler appears damaged or the mouthpiece becomes detached, discard it and use a new inhaler. Do not attempt to repair the device."},
        ]},
    ]
}

ALL_DOCS = [DOC1, DOC2, DOC3, DOC4, DOC5, DOC6]
